### ISSUE TITLE
为什么我提问的两个问题都给删了？

### ISSUE THREAD

**Issue by qiuzy008** [AAChartModel/AAChartCore#10]

**Comment by AAChartModel** [comment]
黑人问号???.jpg

你提的两个问题不是都在这里吗?
   #8   #9

**Comment by AAChartModel** [comment]
除非问题是在太无语,否则我一般不会轻易删除issue

**Comment by qiuzy008** [comment]
好的，已经看见，奇怪的是，我在主目录看不到了

**Comment by AAChartModel** [comment]
![image](https://user-images.githubusercontent.com/16357599/66698722-ffe67b80-ed12-11e9-8dfe-77643a79c894.png)
github 的 issue 专区分为已关闭问题和未关闭问题两个专区.

**Comment by qiuzy008** [comment]
非常感谢作者，现在有个问题是类似饼图的圆环怎么才可以实现到，可以给个demo吗







------------------ 原始邮件 ------------------
发件人: "An An"<notifications@github.com>;
发送时间: 2019年10月12日(星期六) 下午5:10
收件人: "AAChartModel/AAChartCore"<AAChartCore@noreply.github.com>;
抄送: "梦想天空"<759439869@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [AAChartModel/AAChartCore] 为什么我提问的两个问题都给删了？ (#10)





 github 的 issue 专区分为已关闭问题和未关闭问题两个专区.
