### ISSUE TITLE
请问大佬们能默认显示准心么，准心的高度不要超过Y坐标

### ISSUE THREAD

**Issue by bruceLio** [AAChartModel/AAChartCore#100]

**Comment by bruceLio** [comment]
<img width="364" alt="WechatIMG154" src="https://user-images.githubusercontent.com/20415778/121646509-fb65fd80-cac7-11eb-8b32-936de3b4f95b.png">

**Comment by AAChartModel** [comment]
不支持这个功能, 准星线不支持高度的设置. 而且也不支持默认设置准星线
