### ISSUE TITLE
您好, 请教您一个问题. 折线图在没有数据或部分数据的情况下(数据个数达不到X轴定义的刻度个数), 如何完全展示X轴的刻度?

### ISSUE THREAD

**Issue by zxq126** [AAChartModel/AAChartCore#103]
我现在遇到的问题是, 在绘制折线图时, **设置几个数据, X轴就展示几个刻度**, 我有尝试调整X轴的`type`为线性和分类 | 分别设置`tickAmount`, 但是都没有达到效果. 希望您能指点一下如何在没有数据或数据不全的情况下, 完整展示X的所有刻度(x轴刻度总数已知), 不胜感激!

**Comment by AAChartModel** [comment]
没有数据的地方, 用 NSNull 对象占位即可

**Comment by zxq126** [comment]
非常感谢！真是想破头了，当时想过填充0，或者填一组纯0数据（在做一些隐藏处理），没往null这一块想。
