### ISSUE TITLE
当绘制点数超过10000时闪退，会报Render process (16399)'s crash wasn't handled by all associated  webviews, triggering application crash.，这个该怎么解决

### ISSUE THREAD

**Issue by dahaiChang** [AAChartModel/AAChartCore#105]
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/dipper/dipper:9/PKQ1.180729.001/9.9.27:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 16334, tid: 16334, name: .relations.argm  >>> com.relations.argm <<<
signal 5 (SIGTRAP), code 1 (TRAP_BRKPT), fault addr 0x78595b5f54
Abort message: '[FATAL:aw_browser_terminator.cc(81)] Render process (16399)'s crash wasn't handled by all associated  webviews, triggering application crash.
'
    x0  0000007fdf135f38  x1  0000007851269420  x2  0000000000000400  x3  00000078efe323c0
    x4  0000000000000000  x5  75696d6f726863ff  x6  0000000000008000  x7  0080000000000000
    x8  0000000000000000  x9  0000000000000000  x10 0000000000000091  x11 0000000000000000
    x12 0101010101010101  x13 0000000000000008  x14 ffffffffffffffff  x15 0000b91081697b75
    x16 00000078efe301e0  x17 00000078efdc3d48  x18 0000000000000001  x19 0000007fdf1363e0
    x20 0000007fdf1363d8  x21 000000000000008d  x22 00000078efe323c0  x23 000000785b183000
    x24 000000785082eb30  x25 0000007fdf135f01  x26 00000078f51035e0  x27 0000007fdf135f00
    x28 0000007858132669  x29 0000007fdf1363a0
    sp  0000007fdf135ef0  lr  00000078595b5e24  pc  00000078595b5f54

backtrace:
    #00 pc 000000000273cf54  /system/app/WebViewGoogle/WebViewGoogle.apk (offset 0x15ea000)

**Comment by AAChartModel** [comment]
参考 #106
