### ISSUE TITLE
需求：需要在一个页面使用3个折线图分别展示温度、湿度、重量折线图，可上下滑动，且每个绘制点数接近1万，部分机型会出现卡顿，说主线程进行大量耗时操作

### ISSUE THREAD

**Issue by dahaiChang** [AAChartModel/AAChartCore#106]
这个有没有好的解决方案？已经进行了部分优化，在一个页面实现还是会有些许卡顿，效果不太理想

**Comment by AAChartModel** [comment]
由于 AAChartCore 是基于前端图表库 Highcharts 实现的(需要使用 WebView), 所以数据量过大时,可能有性能瓶颈.

**Comment by AAChartModel** [comment]
你可以试试手动引入 `boost.js` 性能增强模块

https://code.highcharts.com/modules/boost.js

参考博客  https://www.highcharts.com/blog/news/175-highcharts-performance-boost/

**Comment by AAChartModel** [comment]
对应的中文博客文档 https://blog.jianshukeji.com/highcharts/highcharts-preformance-boost.html

**Comment by dahaiChang** [comment]
嗯，非常感谢大佬，数据量小的时候，这个库真是没得毛病挑，好用的不得了！

**Comment by dahaiChang** [comment]
已添加增加模块，绘制点数在13000个时，绘制的线会有点模糊，成锯齿状，手势逐渐放大查看至单个点，这个过程会越来越正常。就是需要放大一定比例后绘制的线才正常，目前没发现卡顿，滑动比较流畅，十分感谢！
