### ISSUE TITLE
请问 1.怎样取消图例的点击事件 2.扇形区域点击其他颜色透明度怎么样可以保持不变

### ISSUE THREAD

**Issue by wangswu** [AAChartModel/AAChartCore#108]
1.怎样取消图例的点击事件
2.扇形区域点击其他颜色透明度怎么样可以保持不变

**Comment by AAChartModel** [comment]
> 1.怎样取消图例的点击事件

```java
        aaOptions.plotOptions.series.events = new AASeriesEvents()
                .legendItemClick("function() {\n" +
                        "             return false;\n" +
                        "         }");
```

**Comment by AAChartModel** [comment]
> 2.扇形区域点击其他颜色透明度怎么样可以保持不变

```java
        aaOptions.plotOptions.series.states = new AAStates()
                .inactive(new AAInactive()
                        .enabled(false));
```

**Comment by AAChartModel** [comment]
更新 AAChartCore 最新内容,即可使用这些新增的属性.

**Comment by wangswu** [comment]
感谢大佬



---原始邮件---
发件人: "An ***@***.***&gt;
发送时间: 2021年9月14日(周二) 晚上6:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [AAChartModel/AAChartCore] 请问 1.怎样取消图例的点击事件 2.扇形区域点击其他颜色透明度怎么样可以保持不变 (#108)




 
更新 AAChartCore 至最新内容,即可使用这些新增的属性.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
