### ISSUE TITLE
请问如何自定义AATooltip的样式而不仅仅是自定义AATooltip的文字样式

### ISSUE THREAD

**Issue by John115** [AAChartModel/AAChartCore#118]

**Comment by AAChartModel** [comment]
```java
public class AATooltip {
    public String backgroundColor;
    public String borderColor;
    public Float borderRadius;
    public Float borderWidth;
    public AAStyle style;
...
...
}
```

以上都是设置 AATooltip 外观样式的属性

**Comment by John115** [comment]
AAStyle中的宽高设定无效是因为低于最小值了吗

**Comment by John115** [comment]
> ```java
> public class AATooltip {
>     public String backgroundColor;
>     public String borderColor;
>     public Float borderRadius;
>     public Float borderWidth;
>     public AAStyle style;
> ...
> ...
> }
> ```
> 
> 以上都是设置 AATooltip 外观样式的属性

AAStyle中的宽高设定无效是因为低于最小值了吗

**Comment by AAChartModel** [comment]
你给个设计稿吧, 我来试试看有什么问题
