### ISSUE TITLE
图表数值显示问题

### ISSUE THREAD

**Issue by ZhongYangdev** [AAChartModel/AAChartCore#121]
作者你好，在使用你的开源控件时我发现了一个问题。
安卓**深色模式**下，图表的**数值**文字会多了一层**描边**效果。我尝试调用AAStyle.style()方法设置数值样式属性，改变字体粗细，但是没用。
在你的demo中，也存在这样的问题。可以先将手机设置为深色模式，打开demo点击Custom Style Chart---一些自定义风格样式图表 -> doubleLayerPieChart---双层嵌套扇形图。即可看到问题描述的样子

**Comment by AAChartModel** [comment]
参考 iOS 版本的相同问题:

* https://github.com/AAChartModel/AAChartKit/issues/1036
