### ISSUE TITLE
AATooltip内的this具体是指那个对面

### ISSUE THREAD

**Issue by 619647373** [AAChartModel/AAChartCore#123]
您好，请问下AATooltip对象内formatter函数里面的js代码中的this是指那个对象，只能取出this.x或this.y的值吗，我现在有个场景是额外增加了一个数据字符串设置在series.name（拼接了x抽数据和额外数据）里面的 然后通过分割name和x轴数据对比再显示在tooltip上，发现this.series.name没有任何值，所有请教下里面的this具体是指那个对象。
  
谢谢，期待您的回复

**Comment by AAChartModel** [comment]
https://api.highcharts.com.cn/highcharts/tooltip.formatter.html
