### ISSUE TITLE
Android版本柱状图哪里可以设置固定宽度

### ISSUE THREAD

**Issue by goodBoy520** [AAChartModel/AAChartCore#130]
数据少时，柱状图的宽度就会拉伸的很宽

**Comment by AAChartModel** [comment]
不支持直接设置柱状图📊的宽度, 参考 iOS 版本的 AAChartKit 相同问题:

* https://github.com/AAChartModel/AAChartKit/issues/537

**Comment by goodBoy520** [comment]
那Y轴的左侧可以自定义数据数据显示吗? 还有当数据都为零时，X轴的线会跑到中间，如何给它定义到底部？
