### ISSUE TITLE
dataLabels没有formatter的问题？

### ISSUE THREAD

**Issue by superlu88** [AAChartModel/AAChartCore#141]
安卓的dataLabels怎么没有formatter啊，我想让dataLabels实现最少两位小数，不足补零，iOS的用formatter实现了，然后安卓这边没没有找到这个formatter，怎么解决？

**Comment by superlu88** [comment]
问一下，这个安卓版本的dataLabels怎么没有formatter，怎么处理啊，自己可以加吗？怎么加才能有用呢？求教？？？

**Comment by AAChartModel** [comment]
> 怎么处理啊，自己可以加吗？怎么加才能有用呢？
可以自己家, 模仿着 AATooltip 的 formatter 属性和 setter 方法, 给 AADataLabels 加一个一模一样的就可以了

**Comment by superlu88** [comment]
> > 怎么处理啊，自己可以加吗？怎么加才能有用呢？
> 
> 可以自己加, 模仿着 AATooltip 的 formatter 属性和 setter 方法, 给 AADataLabels 加一个一模一样的就可以了

public String formatter;
public AATooltip formatter(String prop) {
        String pureJSFunctionStr = "(" + prop + ")";
        pureJSFunctionStr = AAJSStringPurer.pureJavaScriptFunctionString(pureJSFunctionStr);
        formatter = pureJSFunctionStr;
        return this;
    }

**Comment by superlu88** [comment]
> > 怎么处理啊，自己可以加吗？怎么加才能有用呢？
> 
> 可以自己加, 模仿着 AATooltip 的 formatter 属性和 setter 方法, 给 AADataLabels 加一个一模一样的就可以了

public String formatter;
public AATooltip formatter(String prop) {
        String pureJSFunctionStr = "(" + prop + ")";
        pureJSFunctionStr = AAJSStringPurer.pureJavaScriptFunctionString(pureJSFunctionStr);
        formatter = pureJSFunctionStr;
        return this;
    }
加上这两个就可以了吗？

**Comment by AAChartModel** [comment]
> 加上这两个就可以了吗？

是的

**Comment by superlu88** [comment]
> 

好的，谢谢。

**Comment by superlu88** [comment]
> > 加上这两个就可以了吗？
> 
> 是的
![image](https://user-images.githubusercontent.com/42953479/180939465-f468c368-46a2-495f-b208-3c093dadbcca.png)
加上了，但是没有用，请问你那边可以加一下试试吗？还是说需要有其它操作？？？
