### ISSUE TITLE
AAChartViewCallBack . chartViewMoveOverEventMessage 不执行

### ISSUE THREAD

**Issue by InnocentYang** [AAChartModel/AAChartCore#148]
对AAChartView对象设置callback，在图表上点击时不会回调 chartViewMoveOverEventMessage。
chartViewDidFinishLoad 是可以正常回调的。

`

        chartView = view.findViewById(R.id.chart_view);
        chartView.callBack = new AAChartView.AAChartViewCallBack() {
            @Override
            public void chartViewDidFinishLoad(AAChartView aaChartView) {
                XLog.tag("Innocent").log(LogLevel.INFO, "chartViewDidFinishLoad = " + aaChartView);
            }

            @Override
            public void chartViewMoveOverEventMessage(AAChartView aaChartView, AAMoveOverEventMessageModel messageModel) {
                String name = messageModel.name;
                String category = messageModel.category;
                Integer index = messageModel.index;

                XLog.tag("Innocent").log(LogLevel.INFO, "name = " + name + ", category = " + category + ", index = " + index);
            }
        };
        chartView.aa_drawChartWithChartModel(getDefaultChartData());
`

**Comment by InnocentYang** [comment]
找到原因了：
`
return new AAChartModel()
                .chartType(AAChartType.Column)
                .stacking(AAChartStackingType.Normal)
                .legendEnabled(true)
                .yAxisGridLineWidth(0)
                .markerRadius(0)
                .categories(categories)
                .colorsTheme(colorsTheme)
                **.touchEventEnabled(true)**
                .series(series);
`

要把触摸事件打开

**Comment by yuexunyu** [comment]
请问一下如果一条柱状图显示两个数据，回调时怎么同时获取两个数据呢？希望能帮忙解惑一下，谢谢

**Comment by AAChartModel** [comment]
@yuexunyu  通过回调获取的 index, 再从AAChartModel 或 AAOptions 的 series  的 data 数组中自己去取值.

**Comment by yuexunyu** [comment]
已收到你的邮件。

**Comment by kuojy** [comment]
柱状图，弹窗设置tooltip.hide(500)；连续点击某一条柱状图2次以上，再点其他位置，chartViewMoveOverEventMessage会回调2次，index分别为上一次连续点击与新位置的index

**Comment by yuexunyu** [comment]
已收到你的邮件。
