### ISSUE TITLE
 请问下安卓的文档在哪里

### ISSUE THREAD

**Issue by ylmyg** [AAChartModel/AAChartCore#153]
请问下项目的文档在哪里，很多属性没有注释，不知道怎么去使用，如AASeriesElement 里面很多属性，不懂是这么意思

**Comment by AAChartModel** [comment]
英文在线文档:
* https://api.highcharts.com/highcharts

**Comment by AAChartModel** [comment]
中文在线文档:
* https://api.highcharts.com.cn/legacy/index.html
