### ISSUE TITLE
折线图顶部的会细不少，花不少时间没找到原因

### ISSUE THREAD

**Issue by gsn516** [AAChartModel/AAChartCore#154]

**Comment by gsn516** [comment]
![微信图片_20220831094040](https://user-images.githubusercontent.com/5070270/187574423-11c9056d-15ce-4935-9c3c-bfb40c9d6db8.png)

**Comment by AAChartModel** [comment]
应该是太靠顶部了, 折线上半部分被覆盖了, 你试试把Y轴最大值设置为 110 或 120

**Comment by gsn516** [comment]
> 应该是太靠顶部了, 折线上半部分被覆盖了, 你试试把Y轴最大值设置为 110 或 120

我设置了yAxisMax(110f)不行，y轴又不能增加，因为稳定值最大是100，超过这个不符合实际

**Comment by AAChartModel** [comment]
那再试试 AAChart 的 marginTop 呢?

**Comment by AAChartModel** [comment]
或者试试 AAYAxis top 属性, 示例如下:

```objc
  aaOptions.yAxis
    .topSet(@"30%")//https://api.highcharts.com/highcharts/yAxis.top
    .heightSet(@"70%")//https://api.highcharts.com/highcharts/yAxis.height
    ;
```

**Comment by gsn516** [comment]
> 或者试试 AAYAxis top 属性, 示例如下:
> 
> ```objc
>   aaOptions.yAxis
>     .topSet(@"30%")//https://api.highcharts.com/highcharts/yAxis.top
>     .heightSet(@"70%")//https://api.highcharts.com/highcharts/yAxis.height
>     ;
> ```

感谢大佬，已经解决，这些设置过了好像还是不行，最后解决方案是
把最大值100改成100.0001，然后让小数点后保留3位，这样就能显示全了
aaYAxis.labels(new AALabels().format("{value:.3f}"));
