### ISSUE TITLE
Android没有设置y轴坐标值的方法

### ISSUE THREAD

**Issue by InnocentYang** [AAChartModel/AAChartCore#155]
有个心率数据的图表，要求y轴范围从0到220，间隔20
iOS有方法可以设置，
AAChartModel.new.yAxisTickPositionsSet(@[@0,@20,@40,@60,@80,@100,@120,@140,@160,@180,@200,@220])
Android没有，只能设置 yMax 和 yMin，没有设置 y轴间隔的方法，
而且，当我设置 yMin=0, yMax=220时，图表显示的 yMax=250。

![AAChartCore_Y轴数值](https://user-images.githubusercontent.com/5811977/187820152-9037ebfc-d15b-4019-823d-97274dd828de.png)

**Comment by AAChartModel** [comment]
```java
public class AAYAxis extends AAAxis {
...
...
    public AAYAxis tickPositions(Object[] prop) {
        tickPositions = prop;
        return this;
    }
}
```

你可以通过 `AAOptions` 的 `AAYAxis` 属性来设置 `tickPositions` 效果也是一样的.  `AAChartModel` 中的 `tickPositions` 只是一个便捷方法, 实际上调用的还是 `AAOptions` 的 `tickPositions`

**Comment by InnocentYang** [comment]
`
// 谢谢，另外跟遇到这个问题的其他猿提一句：默认在y轴数值旁边有个"value"，用AATtitle把它替换掉
AAOptions aaOptions = aaChartModel.aa_toAAOptions();
        aaOptions.tooltip(aaTooltip);
        AAYAxis yAxis = new AAYAxis();
        yAxis.title(new AATitle().text(""));
        yAxis.min(0);
        yAxis.max(220);
        yAxis.tickInterval(20);
        aaOptions.yAxisArray(new AAYAxis[] {yAxis});
`
