### ISSUE TITLE
范围图表设置空值不显示tooltip和tooltip的文字是 "minValue--maxValue  valueSuffix"

### ISSUE THREAD

**Issue by InnocentYang** [AAChartModel/AAChartCore#157]
求助：
心率范围图表，min=82, max=102, suffix=次/分钟
最开始没有没有处理 空值不显示tooltip时，tooltip的文字是：82次/分钟 - 102次/分钟
希望可以做到显示的文字是：82-102次/分钟

![image](https://user-images.githubusercontent.com/5811977/187859481-4c91be61-1836-4585-8808-0825bf5e0bd3.png)

后来使用AAOptions处理空值不显示tooltip，但tooltip的文字只有 min，没有 max，

![image](https://user-images.githubusercontent.com/5811977/187859923-5ef0ed27-e789-4550-843d-1cfc27185f93.png)

![image](https://user-images.githubusercontent.com/5811977/187860208-986f145f-4f84-4a2c-a96b-23658bb14149.png)

**Comment by AAChartModel** [comment]
参考:

* https://github.com/AAChartModel/AAChartKit/issues/781

**Comment by AAChartModel** [comment]
AreaRange 图表和 ColumnRange 图表取值有些类似, 所以可以直接参考以上链接中的示例.

**Comment by InnocentYang** [comment]
谢谢，问题搞定

```
AATooltip aaTooltip = new AATooltip()
                .useHTML(true)
                .formatter("function () {\n" +
                        "        let wholeContentStr = this.points[0].x + '<br/>';\n" +
                        "        let length = this.points.length;\n" +
                        "        let myPointOptions = this.points[0].point.options;\n" +
                        "        let lowValue = myPointOptions.low;\n" +
                        "        let highValue = myPointOptions.high;\n" +
                        "        let thisPoint = this.points[0];\n" +
                        "        if (lowValue != 0 && highValue != 0) {\n" +
                        "            let prefixStr = '<span style=\\\"' + 'color:'+ thisPoint.color + '; font-size:13px\\\"' + '>◉ ';\n" +
                        "            wholeContentStr += prefixStr + thisPoint.series.name + ': ' + lowValue + '--' + highValue + '" + suffix + "' + '<br/>';\n" +
                        "        }\n" +
                        "        return wholeContentStr;\n" +
                        "    }")
                ;
        AAOptions aaOptions = aaChartModel.aa_toAAOptions();
        aaOptions.tooltip(aaTooltip);
```

![image](https://user-images.githubusercontent.com/5811977/188415960-cecce49a-2d2e-4bfd-a261-8ed187819edd.png)

![image](https://user-images.githubusercontent.com/5811977/188416058-8f8ff6f4-0384-426d-b6e9-f0e89f813e5a.png)

**Comment by AAChartModel** [comment]
如果你的空值处不需要显示 tooltip , 可以参考空值占位示例, 

参考:

* https://github.com/AAChartModel/AAChartCore-Kotlin/issues/109
