### ISSUE TITLE
有较为详细的UI配置API文档么

### ISSUE THREAD

**Issue by CodingCodersCode** [AAChartModel/AAChartCore#161]
如题……

一些基础的UI效果，比如线宽，Bar宽度等，没有找到相关的配置API

**Comment by AAChartModel** [comment]
由于 AACharts 系列都是基于 Highcharts 的, 所以 API 以 Highcharts 官方文档为准. 

Highcharts 参考文档:

* https://api.highcharts.com.cn/highcharts (中文官网)
* https://api.highcharts.com/highcharts (英文官网)

**Comment by AAChartModel** [comment]
旧版中文文档:

* https://api.highcharts.com.cn/legacy/index.html

**Comment by ylmyg** [comment]
请问你能看得懂么？这个库很强大，就是很有说明文档，请问安卓的文档怎么看。

**Comment by AAChartModel** [comment]
> 请问你能看得懂么？这个库很强大，就是很有说明文档，请问安卓的文档怎么看。

如果英文看起来有困难的话, 可以直接查看上面的旧版中文文档, 由于 Highcharts 的低版本兼容性做的很好, 所以以上的旧版中文文档基本上也都是仍然有效的. 旧版中文文档基本上包含了主要的属性配置, 常规情况下, 应该能覆盖 90% 的应用场景了.
