### ISSUE TITLE
折线图的  那条折线可以设置渐变颜色吗

### ISSUE THREAD

**Issue by liuhuan8986** [AAChartModel/AAChartCore#164]

**Comment by liuhuan8986** [comment]
我看介绍的效果图好像没有折线是渐变的

**Comment by AAChartModel** [comment]
参考相同问题:
* https://github.com/AAChartModel/AAChartKit/issues/634

**Comment by AAChartModel** [comment]
以上参考示例是 Objective-C 语言版本的, Java 版本的与此同理.
