### ISSUE TITLE
Y轴重定义值问题

### ISSUE THREAD

**Issue by ls895977** [AAChartModel/AAChartCore#169]
重新设置Y轴参数，类似于ios:yAxisTickPositionsSet方法
根据 上一个问题设置 

```java
    val aaOptions: AAOptions = aaChartModel.aa_toAAOptions()
        val yAxis = AAYAxis()
        yAxis.tickPositions = arrayOf(
            "0",
            "20",
            "40",
            "60",
            "80",
            "100"
        )
        yAxis.title(AATitle().text(""))
        yAxis.min(0)
        yAxis.max(100)
        yAxis.tickInterval(20)
        aaOptions.yAxisArray(arrayOf(yAxis))
        mBinding.AAChartView.aa_drawChartWithChartModel(aaChartModel)
```
y轴不生效问题

**Comment by ls895977** [comment]
mBinding.AAChartView.aa_drawChartWithChartModel(aaChartModel)
val aaOptions: AAOptions = aaChartModel.aa_toAAOptions()
val yAxis = AAYAxis()
yAxis.tickPositions = arrayOf(
    "0",
    "20",
    "40",
    "60",
    "80",
    "100"
)
yAxis.title(AATitle().text(""))
yAxis.min(0)
yAxis.max(100)
yAxis.tickInterval(20)
aaOptions.yAxisArray(arrayOf(yAxis))
mBinding.AAChartView.aa_drawChartWithChartOptions(aaOptions) 是这样分开调用？&nbsp;


竹祭
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "An ***@***.***&gt;; 
发送时间: 2022年12月12日(星期一) 下午5:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AAChartModel/AAChartCore] Y轴重定义值问题 (Issue #169)





 
这个时候, 你应该调用 AAChartView 的绘图方法是:
     public void aa_drawChartWithChartOptions(final AAOptions chartOptions)

**Comment by AAChartModel** [comment]
```java
mBinding.AAChartView.aa_drawChartWithChartModel(aaChartModel)
```

这个方法应该可以直接删除了, 否则你就是调用了两次绘制图表的方法, 不是很有必要.
