### ISSUE TITLE
Y轴数据单位刷新后会改变

### ISSUE THREAD

**Issue by wangtingshun** [AAChartModel/AAChartCore#170]
比如，首次加载数据Y轴数据是 1000 、2000、3000类似这种，再次加载数据刷新视图，Y轴数据变为1k 、2k、3k这种，这是什么原因导致的呢，如何统一单位呢

**Comment by AAChartModel** [comment]
这种情况, 有可能是因为你的数据的最大值发生了变换, Highcharts 的 Y轴文字由于要自适应数据, 所以也就跟着发生了格式上的变化, 你可以通过 yAxis 的 Labels 对象的 format 属性来自定义固定不变的文字格式. 参考文档:

* https://api.highcharts.com/highcharts/yAxis.labels.format

**Comment by wangtingshun** [comment]
能贴个示例吗，属性太多了，不知道怎么设置
