### ISSUE TITLE
请问当Y轴数据均为0时，怎么让Y轴0起点在X轴呢？yAxisMin（）没效果

### ISSUE THREAD

**Issue by Dubhe-zwb** [AAChartModel/AAChartCore#177]
![a](https://user-images.githubusercontent.com/126435227/228412210-ce1b5c92-b63e-4817-9cbc-24e3af2e4567.png)
![a1](https://user-images.githubusercontent.com/126435227/228412223-8430e482-9bc7-479e-9ae4-74f916010056.png)
大神，请问怎么让1图的Y轴0起点在x轴，像图2一样？

**Comment by AAChartModel** [comment]
参考:
* https://github.com/AAChartModel/AAChartKit/issues/773
