### ISSUE TITLE
aa_onlyRefreshTheChartDataWithChartOptionsSeriesArray方法无法减去最后加入的AASeriesElement

### ISSUE THREAD

**Issue by wxhwan** [AAChartModel/AAChartCore#191]
我初始化了5个AASeriesElement分别是A,B,C,D,E，有个需求就是我点击一个按钮就减去一个AASeriesElement，每当我要减去第5个AASeriesElement的时候，此时AAChartView无论有多少个AASeriesElement总是无法减去第5个，感觉像是一直持有第5个AASeriesElement，其他4个都是正常的，我只能通过aa_drawChartWithChartOptions方法重绘才不会出现这种情况，请问一下大佬这是啥问题呀

**Comment by wxhwan** [comment]
5个按钮对应着5个AASeriesElement，独立控制对应的AASeriesElement，我点第5个按钮一直无法减去它对应的AASeriesElement，纵使我视图上减的只剩下这第5个了

**Comment by wxhwan** [comment]
此外，开发平台是android

**Comment by AAChartModel** [comment]
> 有个需求就是我点击一个按钮就减去一个AASeriesElement

你这里调用的是 `AAChartView` 的哪个方法?

**Comment by wxhwan** [comment]
这是来自QQ邮箱的假期自动回复邮件。已收到你的邮件

**Comment by wxhwan** [comment]
点击了按钮之后我会创建一个新的数组并填充新的数据，之后我调用AAChartView 的aa_onlyRefreshTheChartDataWithChartOptionsSeriesArray方法，没有再调用其他的方法

**Comment by AAChartModel** [comment]
```java
    public void aa_addElementToChartSeries(AASeriesElement aaSeriesElement) {
        String pureElementJsonStr = new Gson().toJson(aaSeriesElement);
        String javaScriptStr = "addElementToChartSeriesWithElement('"
                + pureElementJsonStr + "')";
        this.safeEvaluateJavaScriptString(javaScriptStr);
    }

    public void aa_removeElementFromChartSeries(Integer elementIndex) {
        String javaScriptStr = "removeElementFromChartSeriesWithElementIndex('"
                + elementIndex + "')";
        this.safeEvaluateJavaScriptString(javaScriptStr);
    }
```

如果想要直接添加 `AASeriesElement` 或移除某一个指定的 `AASeriesElement` , 可以使用 `AAChartView` 中的上面这两个方法, demo 中暂时没有添加使用示例, 不过你可以自行测试一下试试. 感觉你需要的实现的需求, 应该是直接使用这两个方法就可以了. 

这两个方法, 内部调用的实际是这两个 JS 方法:

```js
        function addElementToChartSeriesWithElement(elementStr) {
            var seriesElement = JSON.parse(elementStr);
            aaGlobalChart.addSeries(seriesElement);
        }

        function removeElementFromChartSeriesWithElementIndex(elementIndex) {
            var seriesElement = aaGlobalChart.series[elementIndex];
            if (seriesElement) {
                seriesElement.remove(true);
            }
        }
```

参考对应的在线文档: 
* https://api.highcharts.com/class-reference/Highcharts.Chart.html#addSeries
* https://api.highcharts.com/class-reference/Highcharts.Series#remove

**Comment by wxhwan** [comment]
好的，感谢大佬，我还有个疑问，就是在如何在折线图显示Y坐标轴？我按照“即时刷新图表数据”即时刷新图表数据分类的折线图中的代码去修改，发现虽然会显示Y坐标轴，但是折现图反映出来的数据和我设置的数据对不上，且x轴会有部分超出屏幕，感觉像是被放大了一样；另外我尝试了“通过Options绘图”分类中的customLegendStyle中的代码尝试修改，发现添加图一
![图一](https://github.com/AAChartModel/AAChartCore/assets/149673858/228299ef-2f11-407c-9ca7-669879010ae1)
中的代码也会有Y坐标轴显示，但是会多出很多y轴，就像图二
![图二](https://github.com/AAChartModel/AAChartCore/assets/149673858/543b17d1-7591-4042-bbbb-8bd709d4b6e6)
一样被细分成了很多小方块。我应该怎么实现在不影响原有折线图样式的基础上添加一条Y坐标轴（如图三）
![图三](https://github.com/AAChartModel/AAChartCore/assets/149673858/72946ee6-295a-4e51-863c-303f86fd34ce)
，并且不显示y轴的标题（因为我发现AAChartModel.yAxisVisible这个方法是同是控制Y坐标轴与Y轴标题的显示和隐藏）

**Comment by AAChartModel** [comment]
> 我应该怎么实现在不影响原有折线图样式的基础上添加一条Y坐标轴（如图三）

参考 `AAYAxis` 的这个属性:

```java
    public Object[] tickPositions; // An array defining where the ticks are laid out on the axis. 
```

默认情况下, 是根据你给 `AASeriesElement` 的 `data` 数组中的数据, 自动生成 `Y` 轴的网格线的,  `tickPositions` 则是用来自定义 Y轴的网格线对应的数值的. 参考在线文档:
* https://api.highcharts.com/highcharts/yAxis.tickPositions


如文档所说,  `tickPositions`: An array defining where the ticks are laid out on the axis. This overrides the default behaviour of [tickPixelInterval](https://api.highcharts.com/highcharts/xAxis.tickPixelInterval) and [tickInterval](https://api.highcharts.com/highcharts/xAxis.tickInterval).

**Comment by AAChartModel** [comment]
> 并且不显示y轴的标题（因为我发现AAChartModel.yAxisVisible这个方法是同是控制Y坐标轴与Y轴标题的显示和隐藏）

直接设置 **Y** 轴文字内容为空字符串 `""` 即可.

**Comment by wxhwan** [comment]
> > 我应该怎么实现在不影响原有折线图样式的基础上添加一条Y坐标轴（如图三）
> 
> 参考 `AAYAxis` 的这个属性:
> 
> ```java
>     public Object[] tickPositions; // An array defining where the ticks are laid out on the axis. 
> ```
> 
> 默认情况下, 是根据你给 `AASeriesElement` 的 `data` 数组中的数据, 自动生成 `Y` 轴的网格线的, `tickPositions` 则是用来自定义 Y轴的网格线对应的数值的. 参考在线文档:
> 
> * https://api.highcharts.com/highcharts/yAxis.tickPositions
> 
> 如文档所说, `tickPositions`: An array defining where the ticks are laid out on the axis. This overrides the default behaviour of [tickPixelInterval](https://api.highcharts.com/highcharts/xAxis.tickPixelInterval) and [tickInterval](https://api.highcharts.com/highcharts/xAxis.tickInterval).

不不不，我并不想自定义y轴的数值，因为我的数据是数字，所以我觉得自带的挺好的，我就只是想要显示y轴线，就像x轴一样，因为只显示了x轴而不显示y轴感觉怪怪的可能会被挑毛病

**Comment by AAChartModel** [comment]
> 我就只是想要显示y轴线，就像x轴一样，

那你应该就按照图 1 中的代码进行配置就行了.

>  但是会多出很多y轴，就像图二

至于你这里说的这个问题, 那是因为你配置了次网格线 `minorGrid` , 只要将 `minorGrid` 相关的代码删除即可(因为默认不会显示次网格线 `minorGrid`).

**Comment by AAChartModel** [comment]
Y轴网格线相关内容, 参考 iOS 版本中的相似问题:

* https://github.com/AAChartModel/AAChartKit/issues/1537#issuecomment-1983040560

**Comment by AAChartModel** [comment]
如果你不是想设置**网格线**, 而是想设置 **Y 轴轴线**的话, 参考 AAYAxis 的属性:

```java
    public Number lineWidth; //坐标轴轴线宽度
    public String lineColor; //坐标轴轴线线颜色
```

在线文档: 
* https://api.highcharts.com/highcharts/yAxis.lineColor
* https://api.highcharts.com/highcharts/yAxis.lineWidth

**Comment by wxhwan** [comment]
> 至于你这里说的这个问题, 那是因为你配置了次网格线 `minorGrid` , 只要将 `minorGrid` 相关的代码删除即可(因为默认不会显示次网格线 `minorGrid`).

这个我试过了，我给xAxis和yAxis这两个属性只加了gridLineWidth和gridLineColor方法，结果就是变成了网格状的统计图了（如图一）
![图一](https://github.com/AAChartModel/AAChartCore/assets/149673858/52dfdd64-cd15-4b4d-a860-3c97772497f0)
而我只想要一个y轴（如图二）
![图二](https://github.com/AAChartModel/AAChartCore/assets/149673858/2e5bb0e3-a8e8-420a-9e59-452e1ec4fe37)

**Comment by AAChartModel** [comment]
设置 `xAxis` 的 `gridLineWidth` 网格线宽度为 `0 `, 不就可以隐藏 **X** 轴网格线, 而只剩下 **Y** 轴的网格线了吗?

**Comment by wxhwan** [comment]
> 设置 `xAxis` 的 `gridLineWidth` 网格线宽度为 `0 `, 不就可以隐藏 **X** 轴网格线, 而只剩下 **Y** 轴的网格线了吗?

aaOptions.xAxis
            .gridLineColor(AAColor.DarkGray)
            .gridLineWidth(0)

aaOptions.yAxis
            .gridLineColor(AAColor.DarkGray)
            .gridLineWidth(1)
我试过了，就这段代码，设置了之后Y坐标轴没了，回到初始的那个样子了

**Comment by AAChartModel** [comment]
> 如果你不是想设置**网格线**, 而是想设置 **Y 轴轴线**的话, 参考 `AAYAxis` 的属性:
> 
> ```java
>     public Number lineWidth; //坐标轴轴线宽度
>     public String lineColor; //坐标轴轴线线颜色
> ```
> 
> 在线 API 文档:
> 
> * https://api.highcharts.com/highcharts/yAxis.lineWidth
> * https://api.highcharts.com/highcharts/yAxis.lineColor

Y 轴的坐标轴轴线, 这两个属性你设置了吗?

**Comment by wxhwan** [comment]
哦，可以了，感谢大佬，为了这条线我改了两天了，总算弄好了
