### ISSUE TITLE
Current version

### ISSUE THREAD

**Issue by FMoreiraSouza** [AAChartModel/AAChartCore#194]
I need know current version, because a can't import with SNAPHOT, i have issue with this. I need import like implementation "com.github.AAChartModel:AAChartCore-Kotlin: currentVersion(Any number)") in Kotlin app build.gradle

**Comment by AAChartModel** [comment]
Refer to:

* https://github.com/AAChartModel/AAChartCore/tags

Try this again:
 
```groovy
	dependencies {
	        implementation 'com.github.AAChartModel:AAChartCore:7.2.0'
	}
```

**Comment by FMoreiraSouza** [comment]
Ok, thank you!

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
