### ISSUE TITLE
可以实现重叠柱状图吗

### ISSUE THREAD

**Issue by qizhengzheng** [AAChartModel/AAChartCore#195]
可以实现重叠柱状图吗
![image](https://github.com/AAChartModel/AAChartCore/assets/59305784/0a288b23-db5c-42d7-811e-ceff19ed9dd3)
下面这几种图能实现吗
![image](https://github.com/AAChartModel/AAChartCore/assets/59305784/55889b36-3999-4620-a266-3751668b92a1)
![image](https://github.com/AAChartModel/AAChartCore/assets/59305784/f4ca54cf-5912-48d8-bc03-f55400b14385)
![image](https://github.com/AAChartModel/AAChartCore/assets/59305784/c8a7e97c-8887-4abd-97db-78dfec26e644)

**Comment by AAChartModel** [comment]
堆叠柱状图是支持的, 参考 `OC` 版本的相关问题:
* https://github.com/AAChartModel/AAChartKit/issues/842
* https://github.com/AAChartModel/AAChartKit/issues/685

**Comment by AAChartModel** [comment]
其他几种图形化的柱状图无法支持.

**Comment by qizhengzheng** [comment]
我想要实现叠和echart 中   barGap: '-100%'的效果，

**Comment by AAChartModel** [comment]
> echart 中 barGap: '-100%'的效果

不太明白这是什么效果

**Comment by qizhengzheng** [comment]
柱状图是重叠在一起，不是累加

**Comment by AAChartModel** [comment]
> 柱状图是重叠在一起，不是累加

参考:
* https://github.com/AAChartModel/AAChartKit/issues/1269

**Comment by AAChartModel** [comment]
* https://github.com/AAChartModel/AAChartKit/issues/1271

**Comment by AAChartModel** [comment]
参考 JS 在线示例:
* https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/column-grouping-false/

**Comment by qizhengzheng** [comment]
Java版本的支持吗

> > 柱状图是重叠在一起，不是累加
> 
> 参考:
> 
> * [AAChartTypeColumn 柱状图如何设置使得数据都从y轴原点开始 AAChartKit#1269](https://github.com/AAChartModel/AAChartKit/issues/1269)

**Comment by AAChartModel** [comment]
对应的 `Java` 版本代码如下:

```java
    //https://github.com/AAChartModel/AAChartKit/issues/1269
    public static AAChartModel noMoreGroupingAndOverlapEachOtherColumnChart() {
        return new AAChartModel()
                .chartType(AAChartType.Column)
                .categories(new String[]{"11/23", "11/24", "11/25", "11/26", "11/27", "11/28", "11/29"})
                .yAxisMax(50)
                .yAxisMin(0)
                .borderRadius(5)
                .series(new AAColumn[]{
                        new AAColumn()
                                .name("总做题")
                                .color("#D8D8D8")
                                .data(new Object[]{30, 20, 28, 40, 42, 48, 50})
                                .grouping(false)
                        ,
                        new AAColumn()
                                .name("正确做题")
                                .color("#00D9CD")
                                .data(new Object[]{28, 18, 26, 40, 40, 46, 39})
                });
    }

    //https://github.com/AAChartModel/AAChartKit/issues/1271
    public static AAChartModel noMoreGroupingAndNestedColumnChart() {
        return new AAChartModel()
                .chartType(AAChartType.Column)
                .categories(new String[]{"11/23","11/24", "11/25","11/26","11/27","11/28","11/29"})
                .yAxisMax(50)
                .yAxisMin(0)
                .borderRadius(5)
                .series(new Object[]{
                        new AAColumn()
                                .name("总目标")
                                .color("DeepSkyBlue")
                                .data(new Object[]{30, 20, 28, 40, 42, 48, 50})
                                .grouping(false)
                                .pointPadding(0.05f)
                        ,
                        new AAColumn()
                                .name("完成度")
                                .color("#FF3030") //Firebrick1 color
                                .data(new Object[]{28, 18, 26, 40, 40, 46, 39})
                                .grouping(false)
                                .pointPadding(0.2f)
                });
    }
```

**Comment by AAChartModel** [comment]
以上 `Java` 版本的示例代码, 你都可以在 `AAChartCore` 的 **demo** 中找到.

**Comment by qizhengzheng** [comment]
可以了，谢谢

**Comment by qizhengzheng** [comment]
![image](https://github.com/AAChartModel/AAChartCore/assets/59305784/9184d29f-ef6d-498c-bfbf-0915ac88c148)
怎么配置这样XY轴的name

**Comment by AAChartModel** [comment]
> ![image](https://private-user-images.githubusercontent.com/59305784/343002484-9184d29f-ef6d-498c-bfbf-0915ac88c148.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzODEzOTUsIm5iZiI6MTcxOTM4MTA5NSwicGF0aCI6Ii81OTMwNTc4NC8zNDMwMDI0ODQtOTE4NGQyOWYtZWY2ZC00OThjLWJmYmYtMDkxNWFjODhjMTQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA1NTEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0Y2I0Nzg5ZWJiOTY0NGU0MDk4MDllZTZlYjk3MjY3YjhlNzAzM2M5MTFiY2FmN2ZjMjYzOWEzNDZmM2JkYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mds8QjcoVbBhSINw7PBDiLXdBtuoAua9PkrvBeyY6vQ) 怎么配置这样XY轴的name

参考:
* https://github.com/AAChartModel/AAChartCore/issues/196
