### ISSUE TITLE
如何动态刷新，如开始显示所有特殊点上的label，手指滑动，全部隐藏特殊点上的label，手移开，全部显示

### ISSUE THREAD

**Issue by kedu** [AAChartModel/AAChartCore#199]
如题

**Comment by AAChartModel** [comment]
参考:

* https://github.com/AAChartModel/AAChartKit/issues/1557

**Comment by AAChartModel** [comment]
**Java** 版本的参考此次提交:

* https://github.com/AAChartModel/AAChartCore/commit/3d9b5293290dc9dd5c7f927386d7bc83f947f586
