### ISSUE TITLE
图表可以只可点击不可滑动吗？

### ISSUE THREAD

**Issue by kedu** [AAChartModel/AAChartCore#203]

**Comment by AAChartModel** [comment]
问:
===
* Highcharts 有办法只响应点击事件, 不响应滑动掠过的事件吗? 我的意思是禁用滑动掠过的响应事件, 但是保留点击事件

答:
===
确实，要在 Highcharts 中实现只响应点击事件而不响应鼠标滑动（hover）事件，确实比预想中复杂一些。不过，我们可以通过一些更复杂的配置来实现这一目标。

### 更好的解决方案

Highcharts 并不直接提供禁止鼠标移动触发响应的配置，但我们可以通过以下方式来实现：

1. **手动禁用默认的鼠标 hover 行为**。
2. **在点击事件时手动触发 tooltip**。

### 具体实现步骤

1. **禁用 Hover**：通过 CSS 或 JavaScript 禁用默认的鼠标移动响应。
2. **在点击事件中手动显示 tooltip**：通过手动调用 `tooltip.refresh()` 来显示。

### 📋 实现代码：

```javascript
Highcharts.chart('container', {
    chart: {
        type: 'line',
        events: {
            load: function() {
                const chart = this;

                // 禁用鼠标 hover 的方式
                Highcharts.addEvent(chart.container, 'mousemove', function (e) {
                    e.preventDefault();
                    // 强制关闭 tooltip，避免悬浮时显示
                    chart.tooltip.hide(0);
                });
            }
        }
    },
    plotOptions: {
        series: {
            states: {
                hover: {
                    enabled: false // 禁用默认 hover 状态
                }
            },
            point: {
                events: {
                    click: function() {
                        const chart = this.series.chart;
                        chart.tooltip.refresh(this); // 在点击时手动显示 tooltip
                    }
                }
            },
            marker: {
                enabled: false // 禁用 marker hover
            }
        }
    },
    tooltip: {
        enabled: true,
        hideDelay: 0, // 设置 tooltip 立刻隐藏
        shared: false
    },
    series: [{
        data: [1, 3, 2, 4, 5]
    }]
});
```

### 解释

- **禁用 Hover**: 使用 `mousemove` 事件来阻止默认的鼠标移动行为，并确保 tooltip 不会在移动时显示。
- **手动显示 tooltip**: 在 `click` 事件中手动调用 `tooltip.refresh()` 方法，确保点击时显示 tooltip。

### 🛠️ 预期效果

- **鼠标移动**: 图表不会响应鼠标移动事件，不会显示 tooltip 或触发任何 hover 效果。
- **鼠标点击**: 点击时，`tooltip` 将会显示点击的数据点的信息。

这个解决方案应该更符合你的需求，解决只响应点击事件的问题。

**Comment by AAChartModel** [comment]
以上内容由我整理自在线 AI 工具.

**Comment by AAChartModel** [comment]
调整后, 对应的 **Java** 代码, 参考此次提交内容:
* https://github.com/AAChartModel/AAChartCore/commit/e510c10b8b803359936b0dcb37a97ea4473d0fce
