### ISSUE TITLE
java版本，折线图上每个数据点无法显示小数点

### ISSUE THREAD

**Issue by chuck-0123** [AAChartModel/AAChartCore#22]
我更改了源码的y轴数据储存类型为ArrayList,可以显示图像，但是无法显示数据小数点后面的数据。
这是我添加的数据measureValue: [44.0, 44.0, 44.0, 43.0, 43.0, 43.0, 42.0, 42.0, 43.0, 43.0, 42.0, 42.0, 42.0, 42.0, 42.0, 42.0, 42.0, 42.0, 42.0]

**Comment by AAChartModel** [comment]
麻烦贴一下完整代码(纯文本,不要截图)

**Comment by chuck-0123** [comment]
private ArrayList<Float>value=new ArrayList;
 private ArrayList<String>date=new ArrayList;

AAChartView aaChartView = findViewById(R.id.AAChartView_hum);
        AAChartModel aaChartModel = new AAChartModel()
                //选择图表类型
                .chartType(Line)
                .colorsTheme(new String[]{"#465DBC"})
                //title标题
                .title("")
                //title字体大小
                .titleFontSize(20f)
                //title字体颜色
                .titleFontColor("#0F0F0F")
                //坐标轴字体颜色
                .axesTextColor("#0F0F0F")
                .subtitle("最近三十分钟数据展示")
                //subtitle字体颜色
                .subtitleFontColor("#0F0F0F")
                //subtitle字体大小
                .subtitleFontSize(20f)
                //背景颜色
                .zoomType("xy")
                .backgroundColor("#FFFFFF")
                //数据是否显示
                .dataLabelsEnabled(false)
                //x轴是否显示数据
                .xAxisLabelsEnabled(true)
                //x轴显示的数据间隔
                .xAxisTickInterval(5)
                //y轴是否显示数据
                .yAxisLabelsEnabled(true)
                //y轴标题
                .yAxisTitle("湿度%")
                //y轴最大值
                .yAxisMax(100.0f)
                //y轴最小值
                .yAxisMin(0.0f)
                .yAxisAllowDecimals(true)
                //x轴数据
                .categories(date)
                //y轴数据
                .series(new AASeriesElement[]{
                        new AASeriesElement()
                                .name("湿度")
                                .data(value),
                });

        aaChartView.aa_drawChartWithChartModel(aaChartModel);//绘制图线
    }
                        String measureTime = mobject.getString("measureTime");
                        Float measureValue = Float.valueOf(mobject.getString("measureValue"));
                        if (measureTime.equals("00:00")&&(measureValue==0.0)){
                            break;
                        }
                        else {
                            value.add(measureValue);
                            date.add(measureTime);
                        }

**Comment by AAChartModel** [comment]
## 配置 AAOptions

```java
private AAOptions customLineChartDataLabelsFormat() {
        AAChartModel aaChartModel = new AAChartModel()
                //选择图表类型
                .chartType(AAChartType.Line)
                .colorsTheme(new String[]{"#465DBC"})
                //title标题
                .title("最近三十分钟数据展示")
                //title字体大小
                .titleFontSize(20f)
                //title字体颜色
                .titleFontColor("#0F0F0F")
                //坐标轴字体颜色
                .axesTextColor("#0F0F0F")
                //背景颜色
                .zoomType("xy")
                .backgroundColor("#FFFFFF")
                //数据是否显示
                .dataLabelsEnabled(true)
                //x轴是否显示数据
                .xAxisLabelsEnabled(true)
                //x轴显示的数据间隔
                .xAxisTickInterval(5)
                //y轴是否显示数据
                .yAxisLabelsEnabled(true)
                //y轴标题
                .yAxisTitle("湿度%")
                //y轴最大值
                .yAxisMax(100.0f)
                //y轴最小值
                .yAxisMin(0.0f)
                .yAxisAllowDecimals(true)
                //x轴数据
//                .categories(date)
                //y轴数据
                .series(new AASeriesElement[]{
                        new AASeriesElement()
                                .name("湿度")
                                .data(new Object[]{44.0999, 44.8880, 44.7770, 43.0066, 43.6660, 43.5550, }),
                });

        AAOptions aaOptions = AAOptionsConstructor.configureChartOptions(aaChartModel);
        aaOptions.plotOptions.line.dataLabels.format = "{point.y:.4f} ℃";
        return aaOptions;
    }
```

## 绘制图形

```java
        aaChartView.aa_drawChartWithChartOptions(aaOptions);
```


## 绘图结果
![image](https://user-images.githubusercontent.com/16357599/69203239-c65d2780-0b7e-11ea-9883-b42dc0cb1c41.png)

**Comment by AAChartModel** [comment]
format 格式化字符串的`.4f`表示小数点后保留 4 位

**Comment by AAChartModel** [comment]
**PS:** 你这里的

```java
//title标题
                .title("")
                //title字体大小
                .titleFontSize(20f)
                //title字体颜色
                .titleFontColor("#0F0F0F")
                //坐标轴字体颜色
                .axesTextColor("#0F0F0F")
                .subtitle("最近三十分钟数据展示")
                //subtitle字体颜色
                .subtitleFontColor("#0F0F0F")
                //subtitle字体大小
                .subtitleFontSize(20f)
```

部分配置有点多余,我改成了

```java
               //title标题
                .title("最近三十分钟数据展示")
                //title字体大小
                .titleFontSize(20f)
                //title字体颜色
                .titleFontColor("#0F0F0F")
                //坐标轴字体颜色
                .axesTextColor("#0F0F0F")
```

因为 highCharts 的副标题默认就是隐藏的,所以没有必要将主标题隐藏,然后将副标题字体调大,然后变成主标题,这个操作有点奇怪😄

**Comment by chuck-0123** [comment]
好的，谢谢你，非常感谢！

**Comment by chuck-0123** [comment]
![TIM截图20191120142536](https://user-images.githubusercontent.com/57440035/69214347-aab74880-0ba1-11ea-8f3d-7804c0db87ec.png)
还有一个问题，这个里面的小数是怎么配置的。
