### ISSUE TITLE
请问下怎么样自定义扇形图的颜色？谢谢

### ISSUE THREAD

**Issue by slowhandwc** [AAChartModel/AAChartCore#27]

**Comment by xiaokele** [comment]
return new AAChartModel()
                .chartType(AAChartType.Pie)
                .backgroundColor("#ffffff")
                .title("")
                .subtitle("")
                .dataLabelsEnabled(true)//是否直接显示扇形图数据
                .yAxisTitle("")
                .colorsTheme(new Object[]{"#3AA9FA", "#FF765D", "#FFAD00", "#00DE7C", "#3C7FF6", "#38A9F8", "#FF666C", "#B08CFF", "#30D4F1"})
                .series(new AAPie[]{
                                new AAPie()
                                        .name("数量")
                                        .innerSize("70%")
                                        .size(150f)
                                        .showInLegend(false)
                                        .allowPointSelect(true)
                                        .dataLabels(new AADataLabels()
                                                .enabled(true)
                                                .useHTML(true)
                                                .distance(18f)
                                                .format("<b>{point.name}</b>: <br> {point.percentage:.1f} %"))
                                        .data(dataS)
                                ,
                        }
                );

**Comment by AAChartModel** [comment]
关键语句 

```java
            .colorsTheme(new Object[]{"#3AA9FA", "#FF765D", "#FFAD00", "#00DE7C", "#3C7FF6", "#38A9F8", "#FF666C", "#B08CFF", "#30D4F1"})

```
