### ISSUE TITLE
请问安卓端的AASeriesElement取不到showInLegendSet(NO)IOS却可以你能不能补一下啊！我有个需求要这个属性。或者你告诉我怎么弄？谢谢了好人一生平安啊

### ISSUE THREAD

**Issue by zhouqunhuang** [AAChartModel/AAChartCore#28]
请问安卓端的AASeriesElement取不到showInLegendSet(NO)IOS却可以你能不能补一下啊！我有个需求要这个属性。或者你告诉我怎么弄？谢谢了好人一生平安啊

**Comment by AAChartModel** [comment]
抱歉了兄弟,太晚回复了,可能已经没什么意义了. 在此次提交( https://github.com/AAChartModel/AAChartCore/commit/948501ab30bfb9272301ec13cf8fad4de20cc85c ) 中已为 AASeriesElement 添加 `showInLegend`功能
