### ISSUE TITLE
ChartView doesn't work after enabled minify and shrinkResources

### ISSUE THREAD

**Issue by NeerajItdose** [AAChartModel/AAChartCore#49]
![Screenshot_2020-06-01-17-28-33](https://user-images.githubusercontent.com/51325393/83407004-7dd7ce00-a42d-11ea-9d70-a6a8029984c0.png)

**Comment by AAChartModel** [comment]
> enabled minify and shrinkResources

What do you mean about this? Did you compress the  JS Files of AAChartCore ?
