### ISSUE TITLE
多条曲线时，Y轴数据对不上，各个点的数据偏大

### ISSUE THREAD

**Issue by luyun181** [AAChartModel/AAChartCore#51]

**Comment by AAChartModel** [comment]
重复问题, 参见 https://github.com/AAChartModel/AAChartKit/issues/925

**Comment by luyun181** [comment]
刚找见.stacking(AAChartStackingType.Normal) 去掉就好

**Comment by luyun181** [comment]
还有个问题。曲线上的点可以隐藏吗？ .markerRadius(0f)  这个设完后，选中的点的效果也变的很小，这两个属性是同一个值吗？
