### ISSUE TITLE
向右拖动会出现一片白色区域

### ISSUE THREAD

**Issue by luyun181** [AAChartModel/AAChartCore#52]
![image](https://user-images.githubusercontent.com/19603477/87494782-7c333400-c682-11ea-9ac9-6d02ac0ae302.png)

**Comment by luyun181** [comment]
new AAScrollablePlotArea()
                        .minWidth(700)
                        .scrollPositionX(1f)

minWidth值调小，曲线就消失了。调大就会出现白色空白区

**Comment by AAChartModel** [comment]
AAChartView 本身是继承自 WebView 的,这个白色部分貌似是 WebView 本身的颜色. 在 AAChartCore 中, 你设置图表的 AAChartModel 的背景色 

```java
    public Object  backgroundColor;       //图表背景色

```

实际上设置的是

```html
   <div id="container" style="width:100%; height: 100%;"></div>
        </div>
```
图表绘图区的 div 的颜色, 所以你可以改一下 WebView 本身的背景色试试看看效果.

参考链接: https://stackoverflow.com/questions/10919223/android-webview-background-color

**Comment by luyun181** [comment]
额。。。我改了ChartView 的android:layout_width="500dp"，设置固定宽度。new AAScrollablePlotArea()的minWidth()设置屏幕宽度。貌似白色区域没了
