### ISSUE TITLE
Android Java版本可以缩放，右上角那个 Reset zoom 可以添加一个修改文字的方法么？

### ISSUE THREAD

**Issue by 179098051** [AAChartModel/AAChartCore#58]
如题

**Comment by AAChartModel** [comment]
aaOptions.defaultOptions = new AALang()
                .resetZoom("重置缩放比例")
                ;

**Comment by 179098051** [comment]
大佬流弊 谢谢

**Comment by byron-xie** [comment]
> ```java
> aaOptions.defaultOptions = new AALang()
>                 .resetZoom("重置缩放比例")
>                 ;
> ```

How to hide this ZOOM button
