### ISSUE TITLE
如何设置曲线fillColor

### ISSUE THREAD

**Issue by zhushenwudi** [AAChartModel/AAChartCore#59]
大佬好，aacharts效果很棒，但是我有个问题没有解决

aaChartModel.series(new AASeriesElement[]{
                        new AASeriesElement()
                                     .fillColor(fillColorGradientColor)
                                     .data(new Object[]{-40.0, -24.9, -37.0, -42.4, -40.0, -40.3, -28.0})

aaOptions.yAxis.min(-100F)

设置如上y轴数据后，原点从-100 ~ 0，但是阴影是从y=0出发的，目标是从y=-100出发，请问如何编写

**Comment by AAChartModel** [comment]
设置 AASeriesElement 的 threshold 为 -100 试试

**Comment by AAChartModel** [comment]
https://api.highcharts.com.cn/highcharts#plotOptions.area.threshold

**Comment by zhushenwudi** [comment]
感谢大佬
