### ISSUE TITLE
图表数据变成0时，那条变成0的数据会依附在其他线条上，Android-kotlin

### ISSUE THREAD

**Issue by pressureKai** [AAChartModel/AAChartCore#6]
![image](https://user-images.githubusercontent.com/28721119/62202926-c7462f80-b3bc-11e9-8bee-76749a1cb94c.png)
之后变成下图
![image](https://user-images.githubusercontent.com/28721119/62203285-6d923500-b3bd-11e9-9f11-3054237a761b.png)
下图是隐藏其他数据只显示变为0的数据，证实的确数据发生改变
![image](https://user-images.githubusercontent.com/28721119/62203413-b0eca380-b3bd-11e9-8292-86e2480bdbbe.png)
官方的demo我将数据变为0也会出现这样的情况

**Comment by AAChartModel** [comment]
这个应该不是bug,你把`AAChartModel`的`Stacking`的属性设置为`AAChartStackingType.False`试试.

![](https://user-images.githubusercontent.com/28721119/62203285-6d923500-b3bd-11e9-9f11-3054237a761b.png)

出现这种情况是你使用了图表堆积效果的原因

**Comment by AAChartModel** [comment]
```kotlin


enum class AAChartStackingType(val value: String) {
    False   (""),//没有堆积效果
    Normal  ("normal"),//常规堆积效果
    Percent ("percent"),//百分比堆积效果
}
```

**Comment by AAChartModel** [comment]
>  ![](https://user-images.githubusercontent.com/28721119/62203413-b0eca380-b3bd-11e9-8292-86e2480bdbbe.png)

至于官方的这个效果,则是因为她的数据全为0时,默认显示效果就是这样,其实也可以将数据全为0时的默认效果改成在Y轴的底部(X轴轴线上),只是我忘了怎么弄了.🙂

**Comment by pressureKai** [comment]
![image](https://user-images.githubusercontent.com/28721119/62204158-34f35b00-b3bf-11e9-8fc1-a43e3d9ecf98.png)
额，还是一样的之前我把三种效果都试过了
这个是Percent
![image](https://user-images.githubusercontent.com/28721119/62204369-aa5f2b80-b3bf-11e9-9ac3-94a947ede2ed.png)
官方demo我是把数据改为0
![image](https://user-images.githubusercontent.com/28721119/62204486-d24e8f00-b3bf-11e9-825c-0c27ed8df40a.png)

**Comment by pressureKai** [comment]
Stacking  False 和 normal 是一样的都是会出现重叠的效果，Percent看起来和原来的图差别很大，其实也是重叠了

**Comment by AAChartModel** [comment]
是我这边代码问题,明天改下

**Comment by pressureKai** [comment]
谢谢大神

**Comment by AAChartModel** [comment]
1. 配置数据

```kotlin
     val aaChartModel = AAChartModel()
            .chartType(chartTypeEnum)
            .title("title")
            .subtitle("subtitle")
            .backgroundColor("#4b2b7f")
            .dataLabelEnabled(false)
            .yAxisGridLineWidth(0)
            .legendVerticalAlign(AAChartLegendVerticalAlignType.Bottom)
            .series(arrayOf(
                AASeriesElement()
                    .name("Tokyo")
                    .data(arrayOf(0,0,0,0,0,0,0,0,0,0,0,0)),
                AASeriesElement()
                    .name("NewYork")
                    .data(arrayOf(0.2, 0.8, 5.7, 11.3, 17.0, 22.0, 24.8, 24.1, 20.1, 14.1, 8.6, 2.5)),
                AASeriesElement()
                    .name("London")
                    .data(arrayOf(0.9, 0.6, 3.5, 8.4, 13.5, 17.0, 18.6, 17.9, 14.3, 9.0, 3.9, 1.0)),
                AASeriesElement()
                    .name("Berlin")
                    .data(arrayOf(3.9, 4.2, 5.7, 8.5, 11.9, 15.2, 17.0, 16.6, 14.2, 10.3, 6.6, 4.8))
            )
            )
```

2. 结果:
![image](https://user-images.githubusercontent.com/16357599/62262127-34ec6d00-b44a-11e9-8f51-a6cb23a69d8e.png)

**Comment by pressureKai** [comment]
没问题了

**Comment by AAChartModel** [comment]
👌
