### ISSUE TITLE
为什么x轴第一个label文字有的显示不全有的能显示完全

### ISSUE THREAD

**Issue by wangxihu** [AAChartModel/AAChartCore#62]
两张截图同样的设置
aaXAxis.tickInterval(aaXAxisData.size() / 2);
aaXAxisData是x轴数据源

![1601351617716](https://user-images.githubusercontent.com/17714868/94510907-852bae80-024a-11eb-9623-3f37bd66b425.jpg)

![1601351650319](https://user-images.githubusercontent.com/17714868/94510918-8c52bc80-024a-11eb-9fdb-de3d81dd7883.jpg)

**Comment by AAChartModel** [comment]
你这数据源的数量应该不一样吧, Highcharts 内部计算 每个 Label 的可用显示空间可能也不一样, 你把字体调小一点试试呢

**Comment by wangxihu** [comment]
数据源的数量一样的,字体调到的很小才可以。是跟数据源数量有关吗，数量越多字体得调的越小。
对了ios的AAChartKit在真机上崩溃的bug修复了吗，我看还没有更新呢

**Comment by AAChartModel** [comment]
> ios的AAChartKit在真机上崩溃的bug修复了吗，我看还没有更新呢

问题已解决,参见 https://github.com/AAChartModel/AAChartKit/issues/1028
