### ISSUE TITLE
How to replace the Y axis label "Values"

### ISSUE THREAD

**Issue by SamueldaCostaAraujoNunes** [AAChartModel/AAChartCore#65]
![image](https://user-images.githubusercontent.com/66431643/98162886-bc802180-1ec0-11eb-881b-f5b260ef16d6.png)

I'm using the graph in an android application (kotlin), I looked in the documentation but I couldn't find it. How do I replace "Values" with another String?

**Comment by AAChartModel** [comment]
```objc
   public String  yAxisTitle;            //y 轴标题
```

**Comment by SamueldaCostaAraujoNunes** [comment]
thanks!
