### ISSUE TITLE
怎么修改扇形图底部数据标题的间距（如图红色标记处）

### ISSUE THREAD

**Issue by tom1993721** [AAChartModel/AAChartCore#73]
![image](https://user-images.githubusercontent.com/17629646/104541487-aa5af600-565c-11eb-860f-4d4cedb26f31.png)

**Comment by AAChartModel** [comment]
```java
    public Float itemMarginTop; //图例的每一项的顶部外边距，单位px。 默认是：0.

```

试试 AALegend 的这个属性

**Comment by tom1993721** [comment]
用itemMarginTop结局了第一个问题，还有一个问题，这里的内容用哪个属性去换行？
![image](https://user-images.githubusercontent.com/17629646/104562426-4dbf0180-5683-11eb-9025-b76dab8967a7.png)

**Comment by AAChartModel** [comment]
第二个问题,参考 #75
