### ISSUE TITLE
组件背景透明实现问题

### ISSUE THREAD

**Issue by yjz0217** [AAChartModel/AAChartCore#74]
由于需要跟当前整个页面有个渐变色背景
AAChartModel中的backgroundColor设置为透明  实际还是白色

还有2个小问题就是xy轴如何设置为虚线 折线图中的连接点如何点击后设置其他颜色 谢谢谢谢 

Android java版本

**Comment by The-Silences** [comment]
设置rgba的透明值，然后在源码里设置webview透明属性，以及在xml里设置控件透明值

**Comment by yjz0217** [comment]
> 设置rgba的透明值，然后在源码里设置webview透明属性，以及在xml里设置控件透明值

太感谢了 我都想给你生猴子

**Comment by AAChartModel** [comment]
> 设置rgba的透明值，然后在源码里设置webview透明属性，以及在xml里设置控件透明值

不是有设置透明背景的属性 `isClearBackgroundColor`

```java
    public Boolean isClearBackgroundColor;
```

**Comment by The-Silences** [comment]
> > 设置rgba的透明值，然后在源码里设置webview透明属性，以及在xml里设置控件透明值
> 
> 不是有设置透明背景的属性 `isClearBackgroundColor` 吗?
> 
> ```java
>     public Boolean isClearBackgroundColor;
> ```

好吧  可能是之前没注意到这个属性

**Comment by blackCat-wlc** [comment]
此方法设置后崩溃，因为getBackground()为空
