### ISSUE TITLE
aaOptions.defaultOptions = new AALang()                 .resetZoom("重置缩放比例")                 ; How to hide this ZOOM button

### ISSUE THREAD

**Issue by byron-xie** [AAChartModel/AAChartCore#78]
aaOptions.defaultOptions = new AALang()
                .resetZoom("重置缩放比例")
                ;
How to hide this ZOOM button

**Comment by AAChartModel** [comment]
```java
        Map buttonTheme = new HashMap();
        buttonTheme.put("display","none");
        
        aaOptions.chart.resetZoomButton.theme = buttonTheme;
```

Refer to https://stackoverflow.com/questions/15032914/highcharts-hide-zoom-reset-button-call-zoom-reset-programmatically
