### ISSUE TITLE
AAChart混淆后加载不出图表

### ISSUE THREAD

**Issue by ahan530** [AAChartModel/AAChartCore#97]
-keep class xxx.xxx.xxx.aachartcorelib.* { *; }
-keepattributes *JavascriptInterface*
-keepattributes *Annotation*
-keepclassmembers class xxx.xxx.xxx.aachartcorelib.aachartcreator.AAChartView.AAChartViewCallBack { #解决webview和js的交互问题
   public *;
}
（xxx.xxx.xxx是自己的项目包名）
使用以上混淆规则一样出错，取消混淆就没问题

**Comment by ahan530** [comment]
demo里面没有混淆规则 ，希望博主答疑解惑，感谢

**Comment by ahan530** [comment]
因为兼容老版本，所以包名都是小写

**Comment by ahan530** [comment]
-keep class xxx.xxx.xxx.aachartcorelib.** { *; }

**Comment by dahaiChang** [comment]
请问最后解决了么？同样遇到这个问题，试了几种方法都不行

**Comment by dahaiChang** [comment]
已解决，只需将AAChartCoreLib包下所有的类去混淆即可！
示例：
-keep class xxx.AAChartCoreLib.AAChartCreator.*{*;}
-keep class xxx.AAChartCoreLib.AAChartEnum.*{*;}
-keep class xxx.AAChartCoreLib.AAOptionsModel.*{*;}
-keep class xxx.AAChartCoreLib.AATools.*{*;}
其中xxx更改为自己实际项目所对应包名即可
@AAChartModel @ahan530

**Comment by dahaiChang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
